ANIMATION_DELAY = 2.4

MAX_GRAVITY = 32
GRAVITY_ACC = 1
GRAVITY_FRAME = int(MAX_GRAVITY * 1.25)

PLAYER_W = 32
PLAYER_H = 32
PLAYER_VEL = 4
PLAYER_JUMP_VEL = [
    round(-PLAYER_VEL * 1.6),
    round(-PLAYER_VEL * 1.8)
]

PLAYER_DASH_VEL = PLAYER_VEL * 3
PLAYER_DASH_DURATION = 20
PLAYER_DASH_COOLDOWN = 60
PLAYER_DASH_JUMP_MULT = 1.5
PLAYER_DASH_COYOTE_TIME = 5

TERRAIN_W = 64
TERRAIN_H = 64

FRUIT_W = 32
FRUIT_H = 32
